### PR TITLE
Replace static date with dynamic date

### PR DESCRIPTION
**Pull request by sandervdo**
Having some time left, getting familiar with Symfony and Twig. :smile: Fixed this small issue.

### CODE REVIEW

**Comment by ChristianVermeulen** [comment]
Just resolve conflicts and good to go!

**Comment by sandervdo** [comment]
Crap, please don't mind the shitty commit message. Didn't notice when pushing

**Comment by ChristianVermeulen** [comment]
Hihi, the other merge screwed it up again :see_no_evil:

**Comment by sandervdo** [comment]
Sometimes... Never had this many troubles to get a couple of PRs merged.. Fixed again, I hope the Vagrant one does not screw up...

**Comment by ChristianVermeulen** [comment]
hmm it did again... But I can't see why exactly because it should be able to just update... Maybe because of forking?

**Comment by sandervdo** [comment]
I tried it slightly different now. Hopefully avoiding all these merges.. otherwise you can always cherrypick the changes. :)

**Pull request merged**
