### PR TITLE
Find dojo

### LINKED ISSUE #8: Create new Dojo page
The overview of dojo's needs some work. We will create a full page Google Maps background with all the dojo's marked. On top there will be a layer showing the planned dojo events.

### PR DESCRIPTION
**Pull request by Tmw**
Closes #8 when merged.

- [x] Geocode the address when saving
- [x] Place markers on the map
- [x] Zoom to marken when clicked
- [x] Refactor JS code
- [x] Make sure resizing the window is handled correctly in the map
- [x] Show info window when clicked
- [x] Clicking the marker on the map should open the info window
- [x] Clicking a Dojo should zoom slightly off-cantered since UI is overlapping here
- [x] Update list UI
- [x] Tweak map style a bit
- [x] Make responsive

### CODE REVIEW

**Comment by Tmw** [comment]
If you'd run this query on Live, all Dojo's will be provided with correct latitude and longitude:

```
INSERT INTO `Dojo` (`id`, `geo_lat`, `geo_long`) VALUES
(1, '51.928294', '4.480246'),
(3, '52.158329', '4.493244'),
(4, '52.361771', '4.918187'),
(5, '51.852894', '5.847802'),
(6, '53.110801', '5.590854'),
(7, '52.219253', '6.892886'),
(8, '52.022660', '4.273288'),
(9, '53.198396', '5.778156'),
(10, '52.508104', '6.125044'),
(11, '53.216833', '6.570357'),
(12, '52.008311', '4.362726'),
(13, '53.212944', '6.561545'),
(14, '52.041794', '4.335630'),
(15, '52.158687', '5.380916'),
(16, '52.115424', '5.052702'),
(17, '51.478557', '5.661754'),
(18, '51.659103', '5.616581')
ON DUPLICATE KEY UPDATE geo_lat=VALUES(geo_lat), geo_long=VALUES(geo_long);
```

**Comment by ChristianVermeulen** [comment]
I styled the map and slightly cleared up the dojo list as well.
If you agree as well and tests still pass, I say :shipit: !

screenshot 2015-10-23 23 36 36

**Comment by Tmw** [comment]
Not a fan of the color combination.. Are the addresses in the list visible on mobile when scaled down?

**Comment by ChristianVermeulen** [comment]
No, I took away the actual addresses. I figured they are just overhead since they only become important once you are actually registered or on the verge of registering for a dojo. What do you think? 

As for color combination, I played around with different things e.g. lighter version, totally white, colored markers, but couldn't find anything better so far. Feel free to play around with different colors! I used [Mapstylr](www.mapstylr.com/map-style-editor] for it. You can input the JSON on line 19 of dojos.js to pick it up.

**Comment by Tmw** [comment]
Hmm ok, will play around with it. It a bit too harsh imho. Also, if you're not using the `e` variable inside the callbacks in the JS files, you don't have to declare them. Makes jslint sad :( ;)

**Comment by ChristianVermeulen** [comment]
Oh snap, my bad! I was trying to fix a little hover issue where the bouncing stops if you go over the actual text. But couldn't get the event to stop bubbling through children so removed it again.. Maybe you have an idea to fix it?

**Comment by Tmw** [comment]
Hmm, I missed that. But you were close though: http://jsfiddle.net/gaby/Zse5V/ Ff you want I can take a further look at it though :)

**Comment by ChristianVermeulen** [comment]
It's weird, in our case the hover seems to behave differently. Also, the hover somehow triggered again on mouseout as well, that's why I changed it to mouseenter. If you have time then by all means have a further look but I don't think it's that big of an issue for now :-)

**Comment by ChristianVermeulen** [comment]
I think I know what happens, looking at that JSFiddle, eventhough the child bubbles up, it does trigger the event again (because new hover, this time on child). We should probably find a way to ignore all events on the children, but that might also break mouseleave triggers is there is no margin around the first child....

**Comment by Tmw** [comment]
Hmm, well theres probably a solution.. I'll take a look tomorrow :)

**Comment by Tmw** [comment]
Tuned the colors of the map a bit. Less bight, easier on the eyes imo :) What do you think? also the hover bug is fixed, was an easy fix after al https://github.com/CoderDojoNederland/website/commit/7474264e0ff2882a0087055202912c59bbd30e1d#diff-31279dc2c9352c094c5d16267a0155a0L168

screen shot 2015-10-24 at 21 52 15

**Pull request merged**
